Milestone 2: Personal Portfolio
afikanzoro/Personal_Portfolio pull request #2
Opened 2022-01-14 11:04 UTC by afikanzoro

-Added a project section
Added an About me section

2022-01-14 18:54 UTC, brytebee requested changes
Hi, @afikanzoro👋,

Good job so far coming so far with the progress you've made! 💪💪

## Highlights
You have done amazing in the following:
- proper GitHub flow✔️
- good commit messages✔️
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- **_Please, commit your code more often. It is a good and professional practice especially for working with Teams._**

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-14 18:54 UTC, brytebee commented on index.html
> +      </section>
- [ ] **Required:** These sections and the preceding sections should be centred on the page, but I observed that they are positioned a little to the right. As much as possible, your UI design should be a clone and similar to your chosen template.

Your UI | Figma Template
:---: | :---:
![image](https://user-images.githubusercontent.com/27709832/149562945-6f9eb2bd-3bc8-4c09-8e83-175cf975dba2.png) | ![image](https://user-images.githubusercontent.com/27709832/149562978-133ced38-8534-4c86-bbbb-7614643c4219.png)

2022-01-14 18:54 UTC, brytebee commented on index.html
> +              <h1>My Recent Works</h1>
- [ ] **Required:** Your webpage shouldn't contain more than 1 `h1` tag which should be used for the main header of the page of your website. Any following header should be any of `h2` to `h6`. See the [StackOverflow post.](https://stackoverflow.com/a/503949)
Please, let's search through the code and replace all `h1` which are not the main header. 🏃🏃

2022-01-14 18:54 UTC, brytebee commented on index.html
> +    </section>
- [ ] **Required:** You are required to position your section of projects using flex. At the moment, the positioning is done using grid. Let's play with all available positioning in CSS 🥳

2022-01-14 18:54 UTC, brytebee commented on index.html
> +            <h1>Profesional Art Printing Data</h1>
- [ ] **Required:** As discussed previously, switch `h1` for any header tag from `h2` to `h6`. 💪

2022-01-14 18:54 UTC, brytebee commented on index.html
> +            <h1>About me</h1>
- [ ] **Required:** As discussed previously, switch `h1` for any header tag from `h2` to `h6`. 💪

2022-01-14 18:54 UTC, brytebee commented on index.html
> +            <h1>Language</h1>
- [ ] **Required:** As discussed previously, switch `h1` for any header tag from `h2` to `h6`. 💪

2022-01-14 18:54 UTC, brytebee commented on index.html
> +            <h1>Frameworks</h1>
- [ ] **Required:** As discussed previously, switch `h1` for any header tag from `h2` to `h6`. 💪

2022-01-14 18:54 UTC, brytebee commented on index.html
> +            <h1>Skills</h1>
- [ ] **Required:** As discussed previously, switch `h1` for any header tag from `h2` to `h6`. 💪

2022-01-14 18:54 UTC, brytebee commented on index.html
> +            <h1>Profesional Art Printing Data</h1>
- [ ] **Required:** As discussed previously, switch `h1` for any header tag from `h2` to `h6`. 💪

2022-01-14 18:54 UTC, brytebee commented on index.html
> +            <h1>Profesional Art Printing Data</h1>
- [ ] **Required:** As discussed previously, switch `h1` for any header tag from `h2` to `h6`. 💪

2022-01-14 18:54 UTC, brytebee commented on index.html
> +            <h1>Profesional Art Printing Data</h1>
- [ ] **Required:** As discussed previously, switch `h1` for any header tag from `h2` to `h6`. 💪

2022-01-14 18:54 UTC, brytebee commented on index.html
> +            <h1>Profesional Art Printing Data</h1>
- [ ] **Required:** As discussed previously, switch `h1` for any header tag from `h2` to `h6`. 💪

2022-01-14 18:54 UTC, brytebee commented on index.html
> +              <h1>Profesional Art Printing Data</h1>
- [ ] **Required:** As discussed previously, switch `h1` for any header tag from `h2` to `h6`. 💪

2022-01-14 18:54 UTC, brytebee commented on index.html
> +             </div>
- [ ] **Required:** You have correctly displayed a list of technologies used for this project. 💪  However, it is more [semantic](https://developer.mozilla.org/en-US/docs/Glossary/Semantics) to use `ul` and `li` tags for the purpose of lists.

2022-01-14 18:54 UTC, brytebee commented on index.html
> +           </div>
- [ ] **Required:** As discussed previously, lets swap the `div`s for `ul` and `li` to display the list.

2022-01-14 18:54 UTC, brytebee commented on index.html
> +           </div>
- [ ] **Required:** As discussed previously, lets swap the `div`s for `ul` and `li` to display the list.

2022-01-14 18:54 UTC, brytebee commented on index.html
> +           </div>
- [ ] **Required:** As discussed previously, lets swap the `div`s for `ul` and `li` to display the list.

2022-01-14 18:54 UTC, brytebee commented on index.html
> +           </div>
- [ ] **Required:** As discussed previously, lets swap the `div`s for `ul` and `li` to display the list.

2022-01-14 18:54 UTC, brytebee commented on index.html
> +           </div>
- [ ] **Required:** As discussed previously, let's swap the `div`s for `ul` and `li` to display the list.

2022-01-14 18:54 UTC, brytebee commented on index.html
> +        </div>
- [ ] **Required:** As discussed previously, lets swap the `div`s for `ul` and `li` to display the list.

2022-01-14 18:54 UTC, brytebee commented on index.html
> +        </div>
- [ ] **Required:** As discussed previously, lets swap the `div`s for `ul` and `li` to display the list.

2022-01-14 18:54 UTC, brytebee commented on index.html
> +        </div>
- [ ] **Required:** As discussed previously, let's swap the `div`s for `ul` and `li` to display the list.

2022-01-14 18:54 UTC, brytebee commented on index.html
> +              <button type="button" onclick="index.html">See project</button>
- [ ] **Required:** It would be nice to implement a hover effect on all your `button`s, what do you think?

2022-01-14 19:28 UTC, afikanzoro commented on index.html
> +             </div>
Hi, hope you're doing well. How can i style the boxes individually using <ul>/<li>?

2022-01-14 19:28 UTC, afikanzoro commented on index.html
> +             </div>
ul li

2022-01-15 10:28 UTC, moise10r approved these changes
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

### **Hi @afikanzoro** , 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


### To Highlight :1st_place_medal: 
 
- No Linter errors :heavy_check_mark: 
- Your Design looks awesome, keep rocking :rocket: 



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


- [ OPTIOANL] Please, Write a meaningful title for your pull request and always add a short summary of changes introduced in the pull request. you can check the  [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)
- [OPTIOANL ] Kindly, Add a screenshot of your project to your README file


Cheers and Happy coding!👏👏👏 💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-01-15 10:28 UTC, moise10r commented on index.html
> +          <div class="button">
- [ OPTIOANL] Be careful with blank lines, Do not add blank lines or spaces without a reason. that make your codebase more readable you can check the [HTML & CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md), kindly remove it

2022-01-15 10:28 UTC, moise10r commented on index.html
> +                  when an<br> unknown printer took a standard dummy<br> text.</p>
- [ OPTIONAL]  Great job :clap:  but I think it will be better to have one `main` section which contain all your cards or projects then use `display: grid` to that main container for positioning those projects

2022-01-15 10:28 UTC, moise10r commented on index.html
> +          </div>
- [ OPTIONAL] Kindly, as required by the previous review, us `ul > li` tags on this section instead of `div` tag, make use you change that before merging you PR

2022-01-15 10:47 UTC, merged