Personal Portfolio
afikanzoro/Personal_Portfolio pull request #3
Opened 2022-01-18 16:00 UTC by afikanzoro

- Added a contact form
- Added a social media list section
- The contact form entails a text input for name, email input and a comments section
- Also includes a submit button

2022-01-18 20:39 UTC, Deepakdanger requested changes
Hi @team, 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- Good PR✔️
- Your website looks professional✔️
- All linter is passing ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-18 20:39 UTC, Deepakdanger commented on styles.css
> +  margin-left: 122px;
- [ ] Let remove the border default color `black` and give some border-color same as the original website. 👇 
- Original website
![yuguy](https://user-images.githubusercontent.com/26767383/150014407-a4291c67-a0f7-41d2-973d-040c2d445eb8.PNG)

- Your website
![hgjhj](https://user-images.githubusercontent.com/26767383/150014452-42bb0866-8ceb-4b2b-a545-523ab005eea9.PNG)

2022-01-18 21:17 UTC, rotimiazeez approved these changes
# Hi Team👌, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🎉🎉
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-19 06:11 UTC, alexander16108 approved these changes
Hi @afikanzoro , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

sorry for any inconvenience made by the previous code review

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-19 06:41 UTC, merged